"use client";

import { useMemo, useState } from "react";
import { valideerInitialen } from "@/lib/nakijken/rubric";
import { downloadOudersWord } from "@/lib/ouders/export";
import { AANLEIDINGEN, maakGespreksplanning, maakOudermail, maakVerslag, privacyOuders, type Aanleiding, type Toon } from "@/lib/ouders/templates";

const inputClass = "mt-1 min-h-11 w-full rounded-lg border-2 border-lijn bg-ivoor px-3 py-2 text-base text-tekst focus:outline-none focus:ring-2 focus:ring-marine";
type GesprekState = { doel: string; sterk: string[]; aandacht: string[]; vraag: string; afspraak: string; minuten: 10 | 20 };
type AfspraakState = { wie: string; wat: string; wanneer: string };
type VerslagState = { datum: string; aanwezigen: string; besproken: string; afspraken: AfspraakState[]; vervolg: string };
function Veld({ label, value, onChange, placeholder, multiline = false }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; multiline?: boolean }) {
  return <label className="block text-base font-semibold text-marine">{label}{multiline ? <textarea className={inputClass} rows={3} value={value} placeholder={placeholder} onChange={(e) => onChange(e.target.value)} /> : <input className={inputClass} value={value} placeholder={placeholder} onChange={(e) => onChange(e.target.value)} />}</label>;
}
function Actie({ children, onClick, disabled = false }: { children: React.ReactNode; onClick: () => void; disabled?: boolean }) {
  return <button type="button" disabled={disabled} onClick={onClick} className="min-h-11 rounded-lg bg-marine px-4 py-2 text-base font-semibold text-op-donker transition-colors hover:bg-marine/90 focus:outline-none focus:ring-2 focus:ring-marine disabled:cursor-not-allowed disabled:opacity-50">{children}</button>;
}

export function Oudercontact() {
  const [tab, setTab] = useState<"mail" | "gesprek" | "verslag">("mail");
  const [melding, setMelding] = useState("");
  const [mail, setMail] = useState({ aanleiding: AANLEIDINGEN[0] as Aanleiding, aanhef: "Beste ouder(s)/verzorger(s)", leerling: "", vak: "", observatie: "", observatie2: "", actie: "", toon: "vriendelijk" as Toon, lengte: "normaal" as "kort" | "normaal", naam: "" });
  const [gesprek, setGesprek] = useState<GesprekState>({ doel: "", sterk: ["", "", ""], aandacht: ["", ""], vraag: "", afspraak: "", minuten: 10 });
  const [verslag, setVerslag] = useState<VerslagState>({ datum: "", aanwezigen: "ouder/verzorger en docent", besproken: "", afspraken: [{ wie: "", wat: "", wanneer: "" }], vervolg: "" });
  const mailOutput = useMemo(() => maakOudermail(mail), [mail]);
  const output = useMemo(() => tab === "mail" ? mailOutput.body : tab === "gesprek" ? maakGespreksplanning(gesprek).tekst : maakVerslag(verslag), [tab, mailOutput, gesprek, verslag]);
  const privacy = privacyOuders(output);
  function kopieer(tekst: string) {
    const check = privacyOuders(tekst);
    if (check.blokkeer) { setMelding(`Kopiëren geblokkeerd: ${check.redenen.join(" en ")}.`); return; }
    navigator.clipboard.writeText(tekst).then(() => setMelding("Gekopieerd."), () => setMelding("Kopiëren lukte niet. Selecteer de tekst en kopieer hem zelf."));
  }
  function updateMail(key: string, value: string) { setMail((current) => ({ ...current, [key]: value })); }
  return <div className="mx-auto max-w-5xl space-y-8">
    <header><p className="text-base font-semibold text-marine">Facula · Oudercontact</p><h1 className="mt-2 font-display text-4xl text-marine">Minder tijd aan oudercommunicatie</h1><p className="mt-3 max-w-2xl text-lg text-tekst-zacht">Maak een feitelijke oudermail, bereid een gesprek voor of leg afspraken vast. Gegevens blijven alleen in dit tabblad.</p></header>
    <nav aria-label="Onderdeel oudercontact" className="flex flex-wrap gap-2">{[["mail", "Oudermail"], ["gesprek", "Gesprek voorbereiden"], ["verslag", "Verslag"]].map(([id, label]) => <button type="button" key={id} onClick={() => setTab(id as typeof tab)} className={`min-h-11 rounded-full border-2 px-4 text-base font-semibold focus:outline-none focus:ring-2 focus:ring-marine ${tab === id ? "border-marine bg-marine text-op-donker" : "border-lijn text-marine"}`}>{label}</button>)}</nav>
    {tab === "mail" && <section className="grid gap-6 lg:grid-cols-2"><div className="space-y-4 rounded-xl border-2 border-lijn bg-ivoor p-5"><label className="block text-base font-semibold text-marine">Aanleiding<select className={inputClass} value={mail.aanleiding} onChange={(e) => updateMail("aanleiding", e.target.value)}>{AANLEIDINGEN.map((item) => <option key={item}>{item}</option>)}</select></label><Veld label="Aanhef" value={mail.aanhef} onChange={(v) => updateMail("aanhef", v)} /><Veld label="Initialen of ‘uw kind’" value={mail.leerling} onChange={(v) => updateMail("leerling", v)} placeholder="Bijvoorbeeld L.J." />{mail.leerling && !valideerInitialen(mail.leerling) && mail.leerling !== "uw kind" && <p className="text-base text-fout" role="alert">Gebruik alleen initialen, bijvoorbeeld L.J.</p>}<Veld label="Vak" value={mail.vak} onChange={(v) => updateMail("vak", v)} /><Veld label="Concrete observatie" value={mail.observatie} onChange={(v) => updateMail("observatie", v)} multiline /><Veld label="Tweede observatie, optioneel" value={mail.observatie2} onChange={(v) => updateMail("observatie2", v)} multiline /><Veld label="Gewenste actie" value={mail.actie} onChange={(v) => updateMail("actie", v)} multiline /><Veld label="Naam docent" value={mail.naam} onChange={(v) => updateMail("naam", v)} /><div className="grid gap-3 sm:grid-cols-2"><label className="text-base font-semibold text-marine">Toon<select className={inputClass} value={mail.toon} onChange={(e) => updateMail("toon", e.target.value)}><option value="vriendelijk">Vriendelijk</option><option value="neutraal-zakelijk">Neutraal-zakelijk</option><option value="duidelijk-formeel">Duidelijk-formeel</option></select></label><label className="text-base font-semibold text-marine">Lengte<select className={inputClass} value={mail.lengte} onChange={(e) => updateMail("lengte", e.target.value)}><option value="kort">Kort</option><option value="normaal">Normaal</option></select></label></div></div><Output titel="Mailtekst" onderwerp={mailOutput.subject} tekst={mailOutput.body} privacy={privacy} kopieer={kopieer} mailto={`mailto:?subject=${encodeURIComponent(mailOutput.subject)}&body=${encodeURIComponent(mailOutput.body)}`} /></section>}
    {tab === "gesprek" && <GesprekPanel gesprek={gesprek} setGesprek={setGesprek} output={output} privacy={privacy} setMelding={setMelding} />}
    {tab === "verslag" && <VerslagPanel verslag={verslag} setVerslag={setVerslag} output={output} privacy={privacy} setMelding={setMelding} />}
    <aside className="rounded-xl border-2 border-lijn bg-neutraal-vlak p-5"><h2 className="font-display text-2xl text-marine">Check voor verzenden</h2><ul className="mt-3 list-disc space-y-1 pl-5 text-base"><li>Staat er een concreet, zichtbaar feit?</li><li>Gebruik je geen oordeel of diagnose?</li><li>Staat er één duidelijke actie?</li><li>Is de tekst gericht aan de juiste ouder?</li><li>Kun je de tekst hardop rustig lezen?</li></ul><p className="mt-4 text-base text-tekst-zacht">Gegevens blijven alleen in dit tabblad. Plak de tekst zelf in Magister, Somtoday of je mail.</p></aside>
    {melding && <p role="status" aria-live="polite" className="rounded-xl border-2 border-lijn bg-neutraal-vlak p-4 text-base">{melding}</p>}
  </div>;
}

function Output({ titel, onderwerp, tekst, privacy, kopieer, mailto }: { titel: string; onderwerp?: string; tekst: string; privacy: ReturnType<typeof privacyOuders>; kopieer: (tekst: string) => void; mailto?: string }) { return <section className="space-y-4"><div className="rounded-xl border-2 border-lijn bg-ivoor p-5"><h2 className="font-display text-2xl text-marine">{titel}</h2>{onderwerp && <p className="mt-3 text-base"><strong>Onderwerp:</strong> {onderwerp}</p>}<pre className="mt-4 whitespace-pre-wrap font-sans text-base leading-7 text-tekst">{tekst}</pre>{privacy.blokkeer && <p role="alert" aria-live="polite" className="mt-4 text-base text-fout">Blokkade: {privacy.redenen.join(" en ")}.</p>}{privacy.waarschuwing && <p role="status" aria-live="polite" className="mt-4 text-base text-waarschuwing-tekst">Controleer of er geen volledige naam in staat.</p>}<div className="mt-5 flex flex-wrap gap-3"><Actie disabled={privacy.blokkeer} onClick={() => kopieer(onderwerp || tekst)}>Kopieer {onderwerp ? "onderwerp" : "tekst"}</Actie>{onderwerp && <Actie disabled={privacy.blokkeer} onClick={() => kopieer(tekst)}>Kopieer mail</Actie>}<Actie disabled={privacy.blokkeer} onClick={() => void downloadOudersWord(titel, tekst)}>Download als Word</Actie>{mailto && <a className="flex min-h-11 items-center rounded-lg border-2 border-marine px-4 py-2 text-base font-semibold text-marine focus:outline-none focus:ring-2 focus:ring-marine" href={privacy.blokkeer ? undefined : mailto}>Open in mailprogramma</a>}</div></div></section>; }

function GesprekPanel({ gesprek, setGesprek, output, privacy, setMelding }: { gesprek: GesprekState; setGesprek: (value: GesprekState) => void; output: string; privacy: ReturnType<typeof privacyOuders>; setMelding: (value: string) => void }) { const set = (key: string, value: string | number) => setGesprek({ ...gesprek, [key]: value } as GesprekState); return <section className="grid gap-6 lg:grid-cols-2"><div className="space-y-4 rounded-xl border-2 border-lijn bg-ivoor p-5"><Veld label="Doel gesprek" value={gesprek.doel} onChange={(v) => set("doel", v)} multiline /><Veld label="Sterke punten" value={gesprek.sterk.join("\n")} onChange={(v) => setGesprek({ ...gesprek, sterk: v.split("\n") })} multiline /><Veld label="Aandachtspunten" value={gesprek.aandacht.join("\n")} onChange={(v) => setGesprek({ ...gesprek, aandacht: v.split("\n") })} multiline /><Veld label="Vraag aan ouder" value={gesprek.vraag} onChange={(v) => set("vraag", v)} multiline /><Veld label="Voorstel afspraak" value={gesprek.afspraak} onChange={(v) => set("afspraak", v)} multiline /><label className="text-base font-semibold text-marine">Duur<select className={inputClass} value={gesprek.minuten} onChange={(e) => set("minuten", Number(e.target.value))}><option value={10}>10 minuten</option><option value={20}>20 minuten</option></select></label></div><Output titel="Gespreksplanning" tekst={output} privacy={privacy} kopieer={() => setMelding("Gebruik de printfunctie van de browser voor deze planning.")} /></section>; }
function VerslagPanel({ verslag, setVerslag, output, privacy, setMelding }: { verslag: VerslagState; setVerslag: (value: VerslagState) => void; output: string; privacy: ReturnType<typeof privacyOuders>; setMelding: (value: string) => void }) { const set = (key: string, value: string) => setVerslag({ ...verslag, [key]: value } as VerslagState); return <section className="grid gap-6 lg:grid-cols-2"><div className="space-y-4 rounded-xl border-2 border-lijn bg-ivoor p-5"><Veld label="Datum" value={verslag.datum} onChange={(v) => set("datum", v)} /><Veld label="Aanwezigen (rollen)" value={verslag.aanwezigen} onChange={(v) => set("aanwezigen", v)} /><Veld label="Besproken" value={verslag.besproken} onChange={(v) => set("besproken", v)} multiline /><Veld label="Afspraken, één per regel: wie | wat | wanneer" value={verslag.afspraken.map((a) => `${a.wie} | ${a.wat} | ${a.wanneer}`).join("\n")} onChange={(v) => setVerslag({ ...verslag, afspraken: v.split("\n").map((regel) => { const [wie, wat, wanneer] = regel.split("|"); return { wie: wie?.trim() || "", wat: wat?.trim() || "", wanneer: wanneer?.trim() || "" }; }) })} multiline /><Veld label="Vervolg" value={verslag.vervolg} onChange={(v) => set("vervolg", v)} multiline /></div><Output titel="Verslag" tekst={output} privacy={privacy} kopieer={() => setMelding("Kopiëren lukt pas na een privacycontrole.")} /></section>; }
